services:
  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=easylogs
      - POSTGRES_DB=easylogs
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./easylogs-api/utils/scripts:/docker-entrypoint-initdb.d
    restart: always
  api:
    container_name: easylogs-api
    image: easylogs-api
    build:
      context: ./easylogs-api
      dockerfile: Dockerfile
    environment:
      - EASYLOGS_CONFIGURATION_API_PORT=${EASYLOGS_CONFIGURATION_API_PORT}
    ports:
      - ${EASYLOGS_CONFIGURATION_API_PORT}:5000
    depends_on:
      - database
    restart: always
  client:
    container_name: easylogs-client
    image: easylogs-client
    build: 
      context: ./easylogs-client
      dockerfile: Dockerfile
    environment:
      - EASYLOGS_CONFIGURATION_CLIENT_PORT=${EASYLOGS_CONFIGURATION_CLIENT_PORT}
    ports:
      - ${EASYLOGS_CONFIGURATION_CLIENT_PORT}:4200
    depends_on:
      - api
      - database
    restart: always
